version: '3.9'
services:
  dnsmasq:
    cap_add:
    - NET_ADMIN
    command: --address=/dream/0.0.0.0
    image: andyshinn/dnsmasq
    ports:
    - 53:53/tcp
    - 53:53/udp
    restart: always
  nginx:
    image: jwilder/nginx-proxy
    ports:
    - 80:80/tcp
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    name: dream